#struct_lit_single_line = true
use_small_heuristics = "Max"

max_width=120
fn_call_width=100
attr_fn_like_width=100
struct_lit_width=100
struct_variant_width=100
array_width=60
chain_width=100
single_line_if_else_max_width=75
single_line_let_else_max_width=80

#imports_granularity="Module"
