[package]
name = "sorbit"
version = "0.1.0"
edition = "2024"

[features]
alloc = []
std = ["alloc"]
default = ["std"]

[dependencies]
sorbit_derive = { version = "=0.1.0", path = "../sorbit_derive" }
num = { version = "0.4.3", default-features = false }
