[package]
name = "sorbit_derive_impl"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.101"
quote = "1.0.40"
syn = { version = "2.0.106", features = ["extra-traits", "full"] }
itertools = "0.14.0"
petgraph = "0.8.3"
textwrap = "0.16.2"
