name: build_and_test

on:
  push:
    branches: [ "master", "dev" ]
    tags:
      - v**.**
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        cargo_profile: [dev, release]
        os: [windows-latest, ubuntu-latest]
        features: ["", "--features alloc", "--features alloc,std"]
        include:
          - cargo_profile: dev
            cargo_folder: debug
          - cargo_profile: release
            cargo_folder: release
          - os: windows-latest
            os_name: windows
          - os: ubuntu-latest
            os_name: linux
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --profile ${{ matrix.cargo_profile }} --no-default-features ${{ matrix.features }} --verbose

    - name: Run tests
      run: cargo test --profile ${{ matrix.cargo_profile }} --no-default-features ${{ matrix.features }} --verbose